# Name, title and description
name: Einstein Studios
title: Treats by Heather
description: Treats by Heather

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "assets/img"
    values:
      image: true
      
# include the _pages directory
include: ['_pages']

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# had to use this to get custom domain to project  https://stackoverflow.com/questions/46455900/subdomain-of-website-for-github-pages-project
url: https://treats.einsteinstudios.net

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# baseurl: "/CedarLakeES"
baseurl: ""


# Jekyll theme
theme: jekyll-theme-merlot

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
# Markdown type
markdown: kramdown
